config/routes.rb
WebPosse::Application.routes.draw do
 get "sessions/new"

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

 

  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/signup',  :to => 'users#new'
  match '/users',  :to => 'users#index'
  match '/logout', :to => 'controllers#   application_controller'

root :to => 'sessions#new'

end

app/models/user.rb
require 'digest/sha1'

class User < ActiveRecord::Base
attr_readonly :name
  attr_reader   :password
  attr_accessor :password_confirmation

  validates_presence_of   :name
  validates_length_of     :name, :within => 1..40
  validates_uniqueness_of :name

  validates_length_of     :motto, :within => 0..80

  validates_confirmation_of :password

  def password=(pword)
    @password = pword.strip
    return if @password.length < 6 || @password.length > 40
    self.salt = Digest::SHA1.hexdigest("--#{Time.now.to_s}--#{rand.to_s}--")
    self.salted_password = User.encrypted_password(self.salt, @password)
  end

  def validate_on_create
    if @password.length < 6 || @password.length > 40
      errors.add(:password, "must have between 6 and 40 characters")
    end
  end

  def self.authenticate(name, password)
    user = find(:first, :conditions => [ "name = ?", name ])
    if user
      if user.salted_password != encrypted_password(user.salt, password)
        user = nil
      end
    end
    user
  end

def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  private
    def self.encrypted_password(salt, password)
      Digest::SHA1.hexdigest("--#{salt}--#{password}--")
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  helper :all
 protect_from_forgery # :secret => 'de30b92a0dfd2a772c000dee4ea91d09'

  def login
    session[:user_id] = nil
    if request.post?
     @user = User.authenticate(params[:name], params[:password])
      user = User.authenticate(params[:name], params[:password])
      if user
        session[:user_id] = user.id
      else
        flash[:login_notice] = "Invalid name/password combination"
      end
      redirect_to params[:url]
    else
      redirect_to '/users'
    end
  end

  def logout
    session[:user_id] = nil
    session[:name] = nil
    #
redirect_to :action => "Sign in"
#    redirect_to 'sessions#new'
  end

  helper_method :find_user
  def find_user(id)
    User.find(:first, :conditions => [ "id = ?", id ])
  end

  helper_method :current_user
  def current_user
    @current_user ||= (session[:user_id] ? find_user(session[:user_id]) : nil)
  end

  helper_method :same_user?
  def same_user?(user)
    logged_user = current_user
  #  return true if logged_user.id == user.id
   return true if logged_user && logged_user.id == user.id
  #  return true if  session[:user_id] == user.id
     else
       false
  end
end

app/controllers/pages_controllers.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
    if signed_in?
    @micropost = Micropost.new 
    @feed_items = current_user.feed.paginate(:page => params[:page])
    end
  end

  def contact
    @title = "Contact"
  end

  def about
    @title = "About"

  end

  def help
    @title = "Help"

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = "Sign in"
  end

def destroy
    sign_out
   # reset_session
    redirect_to root_path
  end

def create
  user = User.authenticate(params[:session][:name],
                   params[:session][:password])
                             
    if user.nil?
      flash.now[:error] = "Invalid name."
      @title = "Sign in"
       render 'new'
     else
      # Sign the user in and redirect to the user's show page.
      sign_in user
      redirect_to user
     # render 'index'
      
  end
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #layout 'web_posse'

def log_out
    cookies.delete(:remember_token)
    self.current_user = nil
    redirect_to 'root_path'
  end

def signout
    cookies.delete(:remember_token)
    self.current_user = nil
    @title = "Sign in"
       render 'new'
  end

  # GET /users
  # GET /users.xml
  def index
    @users = User.all

 #   respond_to do |format|
 #     format.html # index.html.erb
  #    format.xml  { render :xml => @users }
  #  end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    @title = "Edit user"

  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
       session[:user_id] = @user.id
        session[:name] = @user.name
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper 
  
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    session[:name] = user.name
    self.current_user = user
    logged_user = current_user
  end
 
  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
    session[:name] = nil
  end
  
def current_user
    @current_user ||= user_from_remember_token
  end

def current_user=(user)
    @current_user = user
  end


def signed_in?
    !current_user.nil?
  end

  private
   def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end

    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'webposse', :media => 'screen' %>
<%= stylesheet_link_tag 'webposse',  :media => 'print' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WebPosse</title>
<!-- <%= stylesheet_link_tag "webposse", :media => 'screen' %> --> 
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <%= render 'layouts/stylesheets' %>
<style type="text/css">
    body { background-color: #A9F5D0; color: #666; text-align: center; font-family: arial, sans-serif; }
    div. {
      width: 25em;
      padding: 0 4em;
      margin: 4em auto 0 auto;
      border: 1px solid #ccc;
      border-right-color: #999;
      border-bottom-color: #999;
    }
    h1 { font-size: 100%; color: #f00; line-height: 1.5em; }
    p.label{ color: #0B3861; }
    p.value{ color: #8A084B; }
    div.actions{ color: #380B61; }
    th { color: #610B0B; }
    td{color: #0B3861;}
  </style>
</head>

<body background-color:tan;>

<%= yield %>

</body>
</html>

app/views/layouts/partials/footer.html.erb
<div class='footer'>
  <p>WebPosse. Brought to you by the VillageTap team.</p>
</div>

app/views/layouts/partials/header.html.erb
<div class='header'>
  <div class='title'>WebPosse</div>
  <div class='login_form'>
    <% logged_user = current_user
       form_tag "/#{controller.controller_name}/#{logged_user ? 'logout' : 'login'}" do %>
      <p class='login'>
        <% if logged_user %>
          User: <span class='user'><%= link_to logged_user.name, logged_user %></span>
          <%= submit_tag 'Log out' %>
        <% else %>
          Name: <%= text_field_tag :name, params[:name], :size => 15, :maxlength => 40 %>
          Password: <%= password_field_tag :password, params[:password], :size => 15,
            :maxlength => 40 %>
          <%= hidden_field_tag :url, url_for %>
          <%= submit_tag 'Log in' %>
        <% end %>
      </p>
<p class='login_notice'><%= flash[:login_notice] %></p>
    <% end %>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, :size =>40, :maxlength => 40 %>
  </div>
  <div class="field">
    <%= f.label :motto %><br />
    <%= f.text_field :motto, :size => 40, :maxlength => 80 %>
  </div>
  <div class="field">
    <%= f.label :pet_name %><br />
    <%= f.text_field :pet_name, :size => 30, :maxlength => 30 %>
  </div>
  <div class="field">
    <%= f.label :mood %><br />
    <%= f.text_field :mood, :size => 40, :maxlength => 30  %>
  </div>
  <div>
    <%= f.label :password, 'Password:' %>
    <%= f.password_field :password, :size => 40, :maxlength => 40 %>
  </div>

  <div>
    <%= f.label :password_confirmation, 'Confirm password:' %>
    <%= f.password_field :password_confirmation, :size => 40, :maxlength => 40 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<% if same_user? @user %>

 <!-- <%= error_messages_for :user %> -->

  <% form_for(@user) do |f| %>
    <div background-color:red;>
      <%= f.label :name, 'Name:' %>
      <%= f.text_field :name, :size => 40, :maxlength => 40,
            :disabled => 'disabled', :class => 'disabled' %>
    </div>

    <div background-color:tan;>
      <%= f.label :motto, 'Motto:' %>
      <%= f.text_field :motto, :size => 40, :maxlength => 80 %>
    </div>

    <div background-color:tan;>
    <%= f.label :pet_name, 'Pet-Name:' %>
    <%= f.text_field :pet_name, :size => 30, :maxlength => 30 %>
   </div>

  </div background-color:tan;>
    <%= f.label :mood, 'Mood:' %>
    <%= f.text_field :mood, :size => 40, :maxlength => 30  %>
  </div>

    <div background-color:brown;>
      <%= f.submit "Update" %>
    
    </div>

 

  <% end %>

<% else %>

  <p class='advise'>
    You must be the Creater of this Record to Change this Information.
  </p>

<% end %>
<%= link_to "Sign Out", signout_path, :method => :delete %>
<%= link_to 'Show', @user %> 
<%= link_to 'Back', users_path %>

<!--
<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %> -->

app/views/users/index.html.erb
<h1>Listing Posse Members</h1>

<!--<%= link_to 'New user', new_user_path %> -->

<img alt="Sample App" src="http://images2.layoutsparks.com/1/164955/the-cartoon-gang-cute.jpg" width="200" height="200"/>
<p>&#160;</p>

<table>
  <tr>
    <th >Name</th>
    <th>Motto</th>
    <th>Pet_Name</th>
    <th>Mood</th>
  </tr>

<% for user in @users %>
  <tr >
    <td><%=h user.name %></td>
    <td><%=h user.motto %></td>
    <td><%=h user.pet_name %></td>
    <td><%=h user.mood %></td>
    <% if session[:name] != nil  %>
     <td><%= link_to 'Show', user %></td>
        <% end %>
    <!--% if current_user.name %-->
    <!--% if session[:name] == user.name %>
    <td><%= link_to 'Show', user %></td-->
     <!--% if session[:user_id] == user.id %-->
     <!--% if same_user? @user  %-->
    <!--% if logged_user.name == h.user.name %-->
    <!--% if logged_user == current_user%-->
     <% if session[:name] == user.name %>
   <td> |  <%= link_to 'Edit', edit_user_path(user) %></td>
       <% end %>
    <% if session[:name] == user.name %>
     <!--% if current_user == user %-->
  <td>  | <%= link_to "delete", user, :method => :delete, 
            :confirm => "You sure?", 
              :title => "Delete #{user.name}" %></td>

    <% end %>
   </tr>

<% end %>

</table>

<p>&#160;</p>
   <% if !signed_in? %>
  <%= link_to 'Back', signin_path %>
     <% end %>
  <!--%= link_to 'Back', users_path %-->
| <%= link_to 'New Member', new_user_path %>
|  <%= link_to "Sign Out", signout_path, :method => :delete %>

<!--table>
  <tr>
    <th>Name</th>
    <th>Motto</th>
    <th>Pet name</th>
    <th>Mood</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.motto %></td>
    <td><%= user.pet_name %></td>
    <td><%= user.mood %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %-->

app/views/users/new.html.erb
<h1>New Posse Member</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>
<%= link_to "Sign Out", signout_path, :method => :delete %>

app/views/users/show.html.erb
<h1>Showing Member</h1>
<div  class='show'  background-color: red;>
  <p class='label'>Name:</p>
  <p class='value'><%=h @user.name %></p>
</div>

<div class='show'>
  <p class='label'>Motto:</p>
  <p class='value'><%=h @user.motto %></p>
</div>

<div class='show'>
  <p class='label'>Pet-Name:</p>
  <p class='value'><%=h @user.pet_name %></p>
</div>

<div class='show'>
  <p class='label'>Mood:</p>
  <p class='value'><%=h @user.mood %></p>
</div>

<div class='show'>
 <!--self.current_user = user
    logged_user = current_user -->
   <!--% if current_user == @user %-->
   <% if session[:name] == @user.name %>
  <!--% if same_user? user  %-->
  <!--% if session[:user_id] == user.id %-->
    <%= link_to 'Edit', edit_user_path(@user) %> 
  <% end %>
  <!--% if session[:user_id] == @user.id %-->
   <% if session[:name] == @user.name %>
  |  <td><%= link_to "delete", @user, :method => :delete, 
            :confirm => "You sure?", 
 
             :title => "Delete #{@user.name}" %></td>
    <% end %>
 | <%= link_to 'Back', users_path %>
 |  <%= link_to "Sign Out", signout_path, :method => :delete %>
</div>



<!--p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Motto:</b>
  <%= @user.motto %>
</p>

<p>
  <b>Pet name:</b>
  <%= @user.pet_name %>
</p>

<p>
  <b>Mood:</b>
  <%= @user.mood %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %> -->